### ISSUE TITLE
NPE StructureModifier on chat message

### ISSUE THREAD

**Issue by hamcoremusic** [games647/mcMMOAction#10]
Hi there, 

Every time I startup my server I get an error from mcMMOAction. I am running Spigot 1.11.2 and the latest mcMMO + mcMMOAction plugin to date. Here is the issue I am getting.

`23.05 07:29:21 [Server] ERROR [mcMMOAction] Unhandled exception occured in onPacketSending(PacketEvent) for mcMMOAction
23.05 07:29:21 [Server] INFO java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketContainer.getChatTypes()Lcom/comphenix/protocol/reflect/StructureModifier;
23.05 07:29:21 [Server] INFO at com.github.games647.mcmmoaction.MessageListener.onPacketSending(MessageListener.java:37) ~[mcMMOAction.jar:?]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.2.1]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1100) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at me.clip.placeholderapi.util.Msg.msg(Msg.java:9) [PlaceholderAPI.jar:?]
23.05 07:29:21 [Server] INFO at me.clip.placeholderapi.commands.spigot.PlaceholderAPICommands.onCommand(PlaceholderAPICommands.java:38) [PlaceholderAPI.jar:?]
23.05 07:29:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
23.05 07:29:21 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]`

**Comment by TuxCoding** [comment]
You have to update ProtocolLib to a 1.12 compatible version.

You can get it from here: ci.dmulloy2.net/job/ProtocolLib/

**Comment by hamcoremusic** [comment]
Hello @games647, I have the latest 4.2.1 ProtocolLb installed, do I need the 1.12 dev release for it to work?

**Comment by TuxCoding** [comment]
Yes, you need a version >= 4.3

**Comment by hamcoremusic** [comment]
Hello again @games647, I have ProtocalLib 4.3 and it is still giving errors.

`[07:51:41] [Server thread/ERROR]: [mcMMOAction] Unhandled exception occured in onPacketSending(PacketEvent) for mcMMOAction
java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[?:1.8.0_112]
	at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:456) ~[ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.events.PacketContainer.getChatTypes(PacketContainer.java:965) ~[ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.github.games647.mcmmoaction.MessageListener.onPacketSending(MessageListener.java:37) ~[mcMMOAction.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:333) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:293) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0-SNAPSHOT-b364]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1100) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at com.gmail.nossr50.util.Motd.displayVersion(Motd.java:38) [mcMMO.jar:?]
	at com.gmail.nossr50.util.Motd.displayAll(Motd.java:21) [mcMMO.jar:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerJoin(PlayerListener.java:389) [mcMMO.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[07:51:41] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_11_R1.PacketPlayOutChat@6244584c[
    a=TextComponent{text='', siblings=[TextComponent{text='[mcMMO] Running version ', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='1.5.07', siblings=[], style=Style{hasParent=true, color=§3, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=1
  ]
`

**Comment by TuxCoding** [comment]
Which build of ProtocolLib do you used the latest?

**Comment by hamcoremusic** [comment]
ProtocolLib.jar:4.3.0-SNAPSHOT-b364

**Comment by TuxCoding** [comment]
It looks like it's a bug in ProtocolLib. You can downgrade mcMMOAction to 1.2.2 here: https://www.spigotmc.org/resources/mcmmoaction.17261/history

There are no changes besides the 1.12 support between them. I'll report this to ProtocolLib.

**Comment by hamcoremusic** [comment]
Thanks @games647, should I downgrade ProtocolLib as well?

**Comment by TuxCoding** [comment]
No that's usually not necessary.

**Comment by hamcoremusic** [comment]
What is the best way to test the ActionBar coming up?

**Comment by TuxCoding** [comment]
You could try to activate an ability by right clicking on the ground in survival mode.

**Comment by hamcoremusic** [comment]
Alright! I just tried it with mcMMOAction 1.22 and ProtocolLib 4.2.1 and it worked. Thank you very much! A couple more things for you... on the plugin page it says the toggle command for chat vs. bar is /mmmoaction, it needs to be changed to /mcmmoaction 👍
