### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by AlphaDelta9** [games647/mcMMOAction#12]
java.lang.NullPointerException
	at com.github.games647.mcmmoaction.MessageListener.readChatPosition(MessageListener.java:74) ~[mcMMOAction.jar:?]
	at com.github.games647.mcmmoaction.MessageListener.onPacketSending(MessageListener.java:41) ~[mcMMOAction.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1100) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:149) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:156) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at fr.neatmonster.nocheatplus.players.PlayerMessageSender.delegateTick(PlayerMessageSender.java:61) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.utilities.OnDemandTickListener.onTick(OnDemandTickListener.java:51) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.utilities.TickTask.notifyListeners(TickTask.java:671) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.utilities.TickTask.run(TickTask.java:713) [NoCheatPlus.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by AlphaDelta9** [comment]
Server Version 1.11.2 / ProtocolLib 4.3.0

**Comment by TuxCoding** [comment]
Just use the older version 1.2.2 https://www.spigotmc.org/resources/mcmmoaction.17261/history
