### ISSUE TITLE
1.12.1 error

### ISSUE THREAD

**Issue by madtomic** [games647/mcMMOAction#15]
[22:51:24] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.ChatSerializer
[22:51:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[22:51:24] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[22:51:24] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:51:24] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:51:24] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[22:51:24] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[22:51:24] [Server thread/WARN]: 	at com.sn1cko.actionbar.methods.theAction.getNmsClass(theAction.java:19)
[22:51:24] [Server thread/WARN]: 	at com.sn1cko.actionbar.methods.theAction.sendAction(theAction.java:61)
[22:51:24] [Server thread/WARN]: 	at com.sn1cko.actionbar.events.playerJoin$1.run(playerJoin.java:39)
[22:51:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[22:51:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[22:51:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[22:51:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[22:51:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[22:51:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[22:51:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by madtomic** [comment]
This spams when player logs onto the server.

**Comment by madtomic** [comment]
I found the source of the error.
