### ISSUE TITLE
i'm a dummy

### ISSUE THREAD

**Issue by cybercyb** [games647/mcMMOAction#26]
when i restart i see this message

[08:56:22] [Server thread/ERROR]: Could not load 'plugins/mcMMOAction.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:314) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-1503de9-53d3ac0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by cybercyb** [comment]
my bad, forgot to download protocollib... ^^'

**Comment by TuxCoding** [comment]
Then close the ticket. This means it's resolved.
