### ISSUE TITLE
Incompatibility with newer McMMO - ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType

### ISSUE THREAD

**Issue by mibby** [games647/mcMMOAction#28]
McMMO dev 291

API changes.
https://github.com/mcMMO-Dev/mcMMO/commit/0d260a74c9ba8ae8fa2c521b4fb9cb1a4fef4484

```
[02:34:35] [Server thread/INFO]: [mcMMOAction] Enabling mcMMOAction v2.4-SNAPSHOT
[02:34:35] [Server thread/ERROR]: Error occurred while enabling mcMMOAction v2.4-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType
	at com.github.games647.mcmmoaction.config.Configuration.loadMessages(Configuration.java:74) ~[?:?]
	at com.github.games647.mcmmoaction.config.Configuration.load(Configuration.java:54) ~[?:?]
	at com.github.games647.mcmmoaction.mcMMOAction.onEnable(mcMMOAction.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:607) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:569) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:430) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:785) ~[patched_1.13.2.jar:git-Paper-489]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-489]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 14 more
[02:34:35] [Server thread/INFO]: [mcMMOAction] Disabling mcMMOAction v2.4-SNAPSHOT
[02:34:35] [Server thread/ERROR]: Error occurred while disabling mcMMOAction v2.4-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at com.github.games647.mcmmoaction.mcMMOAction.saveDisabled(mcMMOAction.java:106) ~[?:?]
	at com.github.games647.mcmmoaction.mcMMOAction.onDisable(mcMMOAction.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:330) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-489]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:607) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:569) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:430) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-489]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:785) ~[patched_1.13.2.jar:git-Paper-489]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by TuxCoding** [comment]
Thanks fixed in https://github.com/games647/mcMMOAction/commit/23e700122036168fee26da51bd8b7a50c0ca841c
