### ISSUE TITLE
console not loading plugin with mcmmo latest jekins build

### ISSUE THREAD

**Issue by comonier** [games647/mcMMOAction#31]
[15:39:11] [Server thread/INFO]: [mcMMOAction] Enabling mcMMOAction v2.3.2*
[15:39:11] [Server thread/ERROR]: Error occurred while enabling mcMMOAction v2.3.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType
	at com.github.games647.mcmmoaction.Configuration.loadMessages(Configuration.java:88) ~[?:?]
	at com.github.games647.mcmmoaction.Configuration.load(Configuration.java:54) ~[?:?]
	at com.github.games647.mcmmoaction.mcMMOAction.onEnable(mcMMOAction.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	... 14 more
[15:39:11] [Server thread/INFO]: [mcMMOAction] Disabling mcMMOAction v2.3.2
[15:39:11] [Server thread/ERROR]: Error occurred while disabling mcMMOAction v2.3.2 (Is it up to date?)
java.lang.NullPointerException: null
	at com.github.games647.mcmmoaction.mcMMOAction.saveDisabled(mcMMOAction.java:99) ~[?:?]
	at com.github.games647.mcmmoaction.mcMMOAction.onDisable(mcMMOAction.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[15:39:11] [Thread-32/INFO]: [HeadsPluginAPI] Done updating interior.json
[15:39:11] [Thread-32/INFO]: [HeadsPluginAPI] Updating color.json
[15:39:11] [Server thread/INFO]: [McMMOExtras] Enabling McMMOExtras v5.3.2*
[15:39:11] [Server thread/ERROR]: Error occurred while enabling McMMOExtras v5.3.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType
	at me.xeroun.mcmmoextras.McMMOExtras.initializeBarAPI(McMMOExtras.java:137) ~[?:?]
	at me.xeroun.mcmmoextras.McMMOExtras.onEnable(McMMOExtras.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-1.13.2-b455.jar:git-Paper-455]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	... 13 more
[15:39:11] [Server thread/INFO]: [McMMOExtras] Disabling McMMOExtras v5.3.2

**Comment by TuxCoding** [comment]
Sorry, but this plugin no longer works with higher mcMMO version, because the same functionality is in the main plugin.
