### ISSUE TITLE
onPacketSending(PacketEvent) for mcMMOAction

### ISSUE THREAD

**Issue by Tim269** [games647/mcMMOAction#36]
== Info ==
Java version: "1.8.0_211"
Servermod version: git-Paper-89 (MC: 1.16.1)
mcMMO version: v1.6.3
mcMMOAction version: v2.4-SNAPSHOT ( from commit 6d50d29 )
ProtocolLib version: v4.5.1

== Error ==
```[17:32:29] [Server thread/INFO]: Schneidertm issued server command: /minecraft:give Schneidertm chest
[17:32:29] [Server thread/ERROR]: [mcMMOAction] Unhandled exception occured in onPacketSending(PacketEvent) for mcMMOAction
java.lang.NullPointerException: null
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:70) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:23) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:91) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:20) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:27) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:15) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:77) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:20) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.16.1.jar:git-Paper-89]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.16.1.jar:git-Paper-89]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:46) ~[patched_1.16.1.jar:git-Paper-89]
	at com.github.games647.mcmmoaction.redirect.RedirectListener.onPacketSending(RedirectListener.java:69) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
	at net.minecraft.server.v1_16_R1.NetworkManager.b(NetworkManager.java:288) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1630) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.EntityPlayer.a(EntityPlayer.java:1691) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.EntityPlayer.sendMessage(EntityPlayer.java:1687) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.CommandListenerWrapper.sendMessage(CommandListenerWrapper.java:207) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.CommandGive.a(SourceFile:75) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.CommandGive.b(SourceFile:35) ~[patched_1.16.1.jar:git-Paper-89]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[patched_1.16.1.jar:git-Paper-89]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.CommandDispatcher.a(CommandDispatcher.java:180) ~[patched_1.16.1.jar:git-Paper-89]
	at org.bukkit.craftbukkit.v1_16_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[patched_1.16.1.jar:git-Paper-89]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-89]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-89]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-89]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[17:32:29] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R1.PacketPlayOutChat@282e66a0[
    a=TranslatableComponent{key='commands.give.success.single', args=[1, TextComponent{text='[', siblings=[TextComponent{text='', siblings=[TranslatableComponent{key='block.minecraft.chest', args=[], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text=']', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=white, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=HoverEvent{action=<action show_item>, value='net.minecraft.server.v1_16_R1.ChatHoverable$c@babca117'}, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='Schneidertm', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell Schneidertm '}, hoverEvent=HoverEvent{action=<action show_entity>, value='net.minecraft.server.v1_16_R1.ChatHoverable$b@f05d4cea'}, insertion=Schneidertm, font=minecraft:default}}], siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]

[17:32:29] [Server thread/INFO]: [Schneidertm: Gave 1 [Chest] to Schneidertm]```

**Comment by TuxCoding** [comment]
Could you update Paper please? THis could already be fixed.

**Comment by Tim269** [comment]
Thank you! Got fixed with git-Paper-90
