### ISSUE TITLE
onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by gp-Airee** [games647/mcMMOAction#40]
Possible duplicate of #36 but I have the latest ver of Paper.
git-Paper-117 on openjdk version "11.0.6" 2020-01-14 LTS
plugin version 2.3.2

```
[15:25:14 ERROR]: [mcMMOAction] Unhandled exception occured in onPacketSending(PacketEvent) for mcMMOAction
java.lang.NoSuchMethodError: 'boolean com.comphenix.protocol.events.PacketContainer.hasMetadata(java.lang.String)'
        at com.github.games647.mcmmoaction.listener.MessageListener.onPacketSending(MessageListener.java:58) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R1.NetworkManager.b(NetworkManager.java:288) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.NetworkManager.dispatchPacket(NetworkManager.java:244) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.NetworkManager.sendPacket(NetworkManager.java:220) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1634) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.PlayerConnection.sendPacket(PlayerConnection.java:1607) ~[patched_1.16.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:227) ~[patched_1.16.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:234) ~[patched_1.16.1.jar:git-Paper-117]
        at com.earth2me.essentials.CommandSource.sendMessage(CommandSource.java:36) ~[?:?]
        at com.earth2me.essentials.textreader.TextPager.showPage(TextPager.java:90) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask$DelayMotdTask.run(EssentialsPlayerListener.java:395) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:321) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-117]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-117]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[15:25:14 ERROR]: Parameters:
  net.minecraft.server.v1_16_R1.PacketPlayOutChat@795dc676[
    a=TextComponent{text='', siblings=[TextComponent{text='    ', siblings=[], style=Style{ color=null, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:de
fault}}, TextComponent{text='Shop @ ', siblings=[], style=Style{ color=aqua, bold=null, italic=false, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}, TextComponent{text='st
ore.theseedmc.com', siblings=[], style=Style{ color=aqua, bold=null, italic=false, underlined=true, strikethrough=null, obfuscated=null, clickEvent=ClickEvent{action=OPEN_URL, value='http://store.theseedmc.com'}, hoverEvent=null, insertion=null, font=min
ecraft:default}}, TextComponent{text='', siblings=[], style=Style{ color=aqua, bold=null, italic=false, underlined=true, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=
null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=CHAT
    c=00000000-0000-0000-0000-000000000000
  ]
```

**Comment by TuxCoding** [comment]
Update to dev build. I fixed it some time ago.

**Comment by gp-Airee** [comment]
> 
> 
> Update to dev build. I fixed it some time ago.

Can you send a direct link to the dev build jar? I thought I found it but I'm having the same issue.

**Comment by TuxCoding** [comment]
https://ci.codemc.io/job/Games647/job/mcMMOAction/

**Comment by gp-Airee** [comment]
> 
> 
> https://ci.codemc.io/job/Games647/job/mcMMOAction/

Yeah issue still present, latest jar from there.

**Comment by gp-Airee** [comment]
Now it just always displays in chat despite my /mmoaction status. No errors or anything.
![javaw_cVlHd5Cgjn](https://user-images.githubusercontent.com/16643747/88702766-0c09c100-d10c-11ea-8fc3-44c6bf2083e6.png)

**Comment by gp-Airee** [comment]
Out of curiosity, why use ProtocolLib to send the action bar rather than Spigot? Bukkit compatibility?

**Comment by TuxCoding** [comment]
It's necessary to intercept the outgoing chat packets from mcMMO.

**Comment by TuxCoding** [comment]
What is your mcMMO version?

**Comment by gp-Airee** [comment]
> 
> 
> What is your mcMMO version?

Classic 1.6.1 as in the above screenshot
