### ISSUE TITLE
IllegalArgumentException: No enum constant

### ISSUE THREAD

**Issue by mibby** [games647/mcMMOAction#7]
Perhaps avoid shutting down if sound isn't found and rather, catch the exception and output that it isn't a valid sound type so you can change / reload the config?

The correct sound type is `ENTITY_EXPERIENCE_ORB_PICKUP` on 1.10.2 for reference.

```
[16:15:07] [Server thread/INFO]: [mcMMOAction] Enabling mcMMOAction v1.1.2
[16:15:07] [Server thread/ERROR]: Error occurred while enabling mcMMOAction v1.1.2 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ORB_PICKUP
    at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_102]
    at org.bukkit.Sound.valueOf(Sound.java:1) ~[patched_1.10.2.jar:git-Paper-876]
    at com.github.games647.mcmmoaction.mcMMOAction.loadConfig(mcMMOAction.java:184) ~[?:?]
    at com.github.games647.mcmmoaction.mcMMOAction.onEnable(mcMMOAction.java:50) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-876]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.10.2.jar:git-Paper-876]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-876]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:375) [patched_1.10.2.jar:git-Paper-876]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:325) [patched_1.10.2.jar:git-Paper-876]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:417) [patched_1.10.2.jar:git-Paper-876]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:382) [patched_1.10.2.jar:git-Paper-876]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328) [patched_1.10.2.jar:git-Paper-876]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched_1.10.2.jar:git-Paper-876]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:583) [patched_1.10.2.jar:git-Paper-876]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[16:15:07] [Server thread/INFO]: [mcMMOAction] Disabling mcMMOAction v1.1.2
```

**Comment by TuxCoding** [comment]
There is already a catch, but it seems to be the wrong one :D

**Comment by TuxCoding** [comment]
Thanks for the hint with the sound name.
