### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by LozePut** [games647/mcMMOAction#8]
If I type /mmoaction, Nothing happens, no error message, nothing in console. All MCMMO messages are still in chat. Nothing special with startup in console.
Using: MCMMOACTION 1.2, MCMMO 1.5.07

**Comment by TuxCoding** [comment]
Could you please attach your server log.

**Comment by LozePut** [comment]
_`[20:40:36] [Server thread/INFO]: Starting minecraft server version 1.10.2
[20:40:36] [Server thread/INFO]: Loading properties
[20:40:36] [Server thread/INFO]: Default game type: SURVIVAL
[20:40:36] [Server thread/INFO]: Generating keypair
[20:40:36] [Server thread/INFO]: Starting Minecraft server on 5.255.70.74:25901
[20:40:36] [Server thread/INFO]: Using epoll channel type
[20:40:36] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-75a8885 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[20:40:37] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca
[20:40:37] [Server thread/INFO]: [HiddenOre] Loading HiddenOre v1.2.2
[20:40:37] [Server thread/INFO]: [CustomEnderChest] Loading CustomEnderChest v1.4.1
[20:40:37] [Server thread/INFO]: [Essentials] Loading Essentials vTeamCity
[20:40:37] [Server thread/INFO]: [GroupManager] Loading GroupManager v2.1.28 (Phoenix)
[20:40:37] [Server thread/INFO]: [ClearLag] Loading ClearLag v2.9.3
[20:40:37] [Server thread/INFO]: [AdvancedArrowTrails] Loading AdvancedArrowTrails v1.8
[20:40:37] [Server thread/INFO]: [AutoMessage] Loading AutoMessage v2.5.5
[20:40:37] [Server thread/INFO]: [WorldBorder] Loading WorldBorder v1.8.6
[20:40:37] [Server thread/INFO]: [CombatTimer] Loading CombatTimer v1.6.1
[20:40:37] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.1.2;e38d98d
[20:40:37] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.4-b527
[20:40:37] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.1.0
[20:40:38] [Server thread/INFO]: [AdvancedPortals] Loading AdvancedPortals v0.0.21
[20:40:38] [Server thread/INFO]: [GuiRedeemMCMMO] Loading GuiRedeemMCMMO v1.5
[20:40:38] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect vTeamCity
[20:40:38] [Server thread/INFO]: [Multiverse-SignPortals] Loading Multiverse-SignPortals v2.4-b523
[20:40:38] [Server thread/INFO]: [VoxelSniper] Loading VoxelSniper v5.171.0-SNAPSHOT
[20:40:38] [Server thread/INFO]: [Multiverse-Inventories] Loading Multiverse-Inventories v2.5-b335
[20:40:38] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[20:40:38] [Server thread/INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild vTeamCity
[20:40:38] [Server thread/INFO]: [mcMMO] Loading mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER}
[20:40:38] [Server thread/INFO]: [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v2.4-b530
[20:40:38] [Server thread/INFO]: [ServerListPlus] Loading ServerListPlus v3.4.7
[20:40:38] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[20:40:38] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[20:40:38] [Server thread/INFO]: [MassiveCore] Loading MassiveCore v2.8.21
[20:40:38] [Server thread/INFO]: TimeUnit.MILLIS_PER_MINUTE: 60000
[20:40:38] [Server thread/INFO]: [EnjinMinecraftPlugin] Loading EnjinMinecraftPlugin v2.7.7
[20:40:38] [Server thread/INFO]: [BottledExp] Loading BottledExp v2.2.2.2
[20:40:38] [Server thread/INFO]: [MassiveHat] Loading MassiveHat v2.8.21
[20:40:38] [Server thread/INFO]: [CompatNoCheatPlus] Loading CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83
[20:40:38] [Server thread/INFO]: [mcMMOAction] Loading mcMMOAction v1.2.1
[20:40:38] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.2.1
[20:40:38] [Server thread/INFO]: [NoCheatPlus] Loading NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1022
[20:40:38] [Server thread/INFO]: onLoad: Early set up of static API, configuration, logging.
[20:40:38] [Server thread/INFO]: [NoCheatPlus] Logging system initialized.
[20:40:38] [Server thread/INFO]: [NoCheatPlus] Detected Minecraft version: 1.10.2
[20:40:38] [Server thread/INFO]: [Factions] Loading Factions v2.8.21
[20:40:38] [Server thread/INFO]: [PvPReward] Loading PvPReward v1.9.0
[20:40:38] [Server thread/INFO]: [Bounty] Loading Bounty v4.1.2
[20:40:38] [Server thread/INFO]: [CratesPlus] Loading CratesPlus v4.2
[20:40:38] [Server thread/INFO]: [ScoreboardStats] Loading ScoreboardStats v0.9.14
[20:40:38] [Server thread/INFO]: [RandomTP] Loading RandomTP v2.3 - noID
[20:40:38] [Server thread/INFO]: [SilkSpawners] Loading SilkSpawners v3.7.3
[20:40:38] [Server thread/INFO]: [CustomEnderChest] Enabling CustomEnderChest v1.4.1
[20:40:38] [Server thread/INFO]: [CustomEnderChest] Loading the config file...
[20:40:38] [Server thread/INFO]: [CustomEnderChest] Config loaded successfully!
[20:40:38] [Server thread/INFO]: [CustomEnderChest] Using FlatFile system for data.
[20:40:38] [Server thread/INFO]: [CustomEnderChest] CustomEnderChest loaded successfully!
[20:40:38] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.1.0
[20:40:38] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[20:40:38] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER}
[20:40:38] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[20:40:38] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[20:40:38] [Server thread/INFO]: [Vault] [Permission] GroupManager found: Waiting
[20:40:38] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[20:40:47] [Server thread/INFO]: [ServerListPlus] Successfully loaded!
[20:40:47] [Server thread/INFO]: [ServerListPlus] ServerListPlus v3.4.7 enabled.
[20:40:47] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[20:40:47] [Server thread/INFO]: [EnjinMinecraftPlugin] Enabling EnjinMinecraftPlugin v2.7.7
[20:40:47] [Server thread/INFO]: [EnjinMinecraftPlugin] MC 1.3 or above found, enabling version 2 XP handling.
[20:40:47] [Server thread/INFO]: [EnjinMinecraftPlugin] MC 1.7.2 or above found, enabling version 2 log handling.
[20:40:47] [Server thread/INFO]: [EnjinMinecraftPlugin] Couldn't find the TuxTwoLib plugin. Only able to give items to online players only.
[20:40:47] [Server thread/WARN]: [EnjinMinecraftPlugin] Economy plugin is not enabled.
[20:40:47] [Server thread/INFO]: [BottledExp] Enabling BottledExp v2.2.2.2
[20:40:47] [Server thread/INFO]: [BottledExp] Version 2.2.2.2 has been enabled
[20:40:47] [Server thread/INFO]: [BottledExp] Using GroupManager via Vault.
[20:40:47] [Server thread/INFO]: [MassiveHat] Enabling MassiveHat v2.8.21
[20:40:47] [Server thread/INFO]: [MassiveHat 2.8.21] === ENABLE START ===
[20:40:47] [Server thread/INFO]: [MassiveHat 2.8.21] === ENABLE COMPLETE (Took 7ms) ===
[20:40:47] [Server thread/INFO]: [CompatNoCheatPlus] Enabling CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83
[20:40:47] [Server thread/INFO]: [cncp] Ensured that the following plugin is enabled: WorldGuard
[20:40:47] [Server thread/INFO]: [cncp] Registered hook(NCPHook might get added later): mcMMO(default) / 2.1
[20:40:47] [Server thread/INFO]: [cncp] Registered hook(NCPHook might get added later): BlockBreak(default) / 1.1
[20:40:47] [Server thread/INFO]: [cncp] Registered hook(NCPHook might get added later): BlockPlace(default) / 1.0
[20:40:47] [Server thread/INFO]: [cncp] Registered hook(NCPHook might get added later): InstaBreak(default) / 1.0
[20:40:47] [Server thread/INFO]: [cncp] Registered hook(NCPHook might get added later): EntityDamageByEntity(default) / 0.0
[20:40:47] [Server thread/INFO]: [CompatNoCheatPlus] CompatNoCheatPlus v6.6.2-RC-sMD5NET-b83 is enabled. Some hooks might get registered with NoCheatPlus later on.
[20:40:47] [Server thread/INFO]: [mcMMOAction] Enabling mcMMOAction v1.2.1
[20:40:47] [Server thread/ERROR]: Error occurred while enabling mcMMOAction v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
    at com.github.games647.mcmmoaction.mcMMOAction.getLocalizedMessage(mcMMOAction.java:168) ~[?:?]
    at com.github.games647.mcmmoaction.mcMMOAction.loadingByIdentifier(mcMMOAction.java:157) ~[?:?]
    at com.github.games647.mcmmoaction.mcMMOAction.loadAllMessages(mcMMOAction.java:85) ~[?:?]
    at com.github.games647.mcmmoaction.mcMMOAction.onEnable(mcMMOAction.java:52) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:358) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:320) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:404) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:369) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:324) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:243) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-beta3-os.jar:git-Bukkit-75a8885]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_66]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_66]
    ... 15 more
[20:40:47] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.2._

**Comment by LozePut** [comment]
Removed some shit about other plugins ;) Only the end is about MCMMOACTION. Its ask of it is up to date, I just downloaded the lasted version from spigot.

**Comment by TuxCoding** [comment]
You don't use Spigot.

**Comment by TuxCoding** [comment]
Spigot includes the Bungee cord chat api

**Comment by LozePut** [comment]
Is there an bukkit version?

**Comment by TuxCoding** [comment]
No why not Spigot?
